#!/bin/sh
set -e

case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


set -e

. /usr/share/debconf/confmodule

APPLICATION=`echo $DPKG_MAINTSCRIPT_PACKAGE | sed 's/multiflexi-//'`
for file in `ls /usr/lib/$APPLICATION/multiflexi/*.json`
do
	multiflexi-json2app $file
done



#DEBHELPER#

exit 0
